use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

mod generation;
pub use generation::generate;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationRequest {
    pub source: PathBuf,
    pub output: PathBuf,
}

impl GenerationRequest {
    pub fn new(source: impl Into<PathBuf>, output: impl Into<PathBuf>) -> Self {
        Self {
            source: source.into(),
            output: output.into(),
        }
    }

    pub fn source_path(&self) -> &Path {
        &self.source
    }

    pub fn output_path(&self) -> &Path {
        &self.output
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationResult {
    pub files: Vec<PathBuf>,
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum GenerationError {
    #[error("could not read source document: {0}")]
    Ingestion(#[from] IngestionError),
    #[error("could not create generated repository: {0}")]
    CreateOutput(String),
    #[error("generated output already exists and is not empty: {0}")]
    OutputExists(PathBuf),
    #[error("could not write generated file {path}: {message}")]
    Write { path: PathBuf, message: String },
}

pub(crate) fn write_file(
    root: &Path,
    relative: &str,
    contents: &str,
    generated: &mut Vec<PathBuf>,
) -> Result<(), GenerationError> {
    let path = root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| GenerationError::Write {
            path: parent.to_path_buf(),
            message: error.to_string(),
        })?;
    }
    fs::write(&path, contents).map_err(|error| GenerationError::Write {
        path: path.clone(),
        message: error.to_string(),
    })?;
    generated.push(PathBuf::from(relative));
    Ok(())
}

fn digest(contents: &str) -> String {
    let digest = Sha256::digest(contents.as_bytes());
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

pub(crate) fn render_rust_cargo(spec: &ApiSpec) -> String {
    format!(
        "[package]\nname = \"{}-sdk\"\nversion = \"0.1.0\"\nedition = \"2024\"\nrust-version = \"1.97\"\n\n[lib]\npath = \"src/lib.rs\"\n",
        slug(&spec.title)
    )
}

pub(crate) fn render_rust_lock(spec: &ApiSpec) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"{}-sdk\"\nversion = \"0.1.0\"\n",
        slug(&spec.title)
    )
}

pub(crate) fn render_rust_client(spec: &ApiSpec) -> String {
    let methods = spec
        .operations
        .iter()
        .map(|operation| {
            format!(
                "    pub fn {}(&self) -> Result<(), SdkError> {{\n        Err(SdkError::TransportNotImplemented)\n    }}\n",
                rust_identifier(&operation.operation_id)
            )
        })
        .collect::<String>();
    format!(
        "#[derive(Debug, Default)]\npub struct Client;\n\n#[derive(Debug, PartialEq, Eq)]\npub enum SdkError {{\n    TransportNotImplemented,\n}}\n\nimpl Client {{\n{}\n}}\n",
        methods
    )
}

pub(crate) fn rust_identifier(value: &str) -> String {
    let mut identifier = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_uppercase() && index > 0 {
            identifier.push('_');
        }
        identifier.push(character.to_ascii_lowercase());
    }
    identifier
}

pub(crate) fn render_config(spec: &ApiSpec) -> String {
    format!(
        "project:\n  name: {}-sdk\n  version: 0.1.0\n\nspec:\n  path: api/openapi.yaml\n  allow_remote_refs: false\n\ntargets: [rust]\n\nrelease:\n  enabled: true\n  crates_io:\n    enabled: true\n    package: {}-sdk\n  pypi:\n    enabled: false\n    package: {}-sdk\n  npm:\n    enabled: false\n    package: {}-sdk\n    publish_provenance: true\n  github:\n    enabled: true\n    workflow: release.yml\n",
        slug(&spec.title),
        slug(&spec.title),
        slug(&spec.title),
        slug(&spec.title),
    )
}

pub(crate) fn render_readme(spec: &ApiSpec) -> String {
    format!(
        "# {} SDK\n\nGenerated by GodSDK from OpenAPI {}.\n\n```sh\ncargo test --manifest-path sdk/rust/Cargo.toml\n```\n",
        spec.title, spec.openapi_version
    )
}

pub(crate) fn render_manifest(
    root: &Path,
    source: &str,
    files: &[PathBuf],
) -> Result<String, GenerationError> {
    let entries = files
        .iter()
        .filter(|path| path.to_string_lossy() != ".godsdk/manifest.json")
        .map(|path| {
            let contents = fs::read_to_string(root.join(path)).map_err(|error| {
                GenerationError::Write {
                    path: root.join(path),
                    message: error.to_string(),
                }
            })?;
            Ok(format!(
                "    {{\"path\":\"{}\",\"target\":\"{}\",\"template\":\"rust/vertical-slice\",\"sha256\":\"{}\"}}",
                path.to_string_lossy(),
                if path.starts_with("sdk/rust") { "rust" } else { "shared" },
                digest(&contents)
            ))
        })
        .collect::<Result<Vec<_>, GenerationError>>()?
        .join(",\n");
    Ok(format!(
        "{{\n  \"schema_version\": 1,\n  \"generator_version\": \"0.1.0\",\n  \"template_set_version\": \"0.1.0\",\n  \"input\": {{\"path\": \"api/openapi.yaml\", \"sha256\": \"{}\", \"resolved_refs\": []}},\n  \"targets\": [\"rust\"],\n  \"governance\": {{\"godlint\": \"0.7.0\", \"godharness\": \"0.1.6\", \"bundle_version\": \"0.1.0\"}},\n  \"files\": [\n{}\n  ]\n}}\n",
        digest(source),
        entries
    ))
}

fn slug(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApiSpec {
    pub openapi_version: String,
    pub title: String,
    pub version: String,
    pub operations: Vec<Operation>,
    pub references: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Operation {
    pub operation_id: String,
    pub method: HttpMethod,
    pub path: String,
    pub parameters: Vec<Parameter>,
    pub request_body: bool,
    pub response_statuses: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum HttpMethod {
    Delete,
    Get,
    Head,
    Options,
    Patch,
    Post,
    Put,
    Trace,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Parameter {
    pub name: String,
    pub location: ParameterLocation,
    pub required: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParameterLocation {
    Query,
    Header,
    Path,
    Cookie,
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum IngestionError {
    #[error("could not read OpenAPI document {path}: {message}")]
    Read { path: PathBuf, message: String },
    #[error("could not parse OpenAPI document: {0}")]
    Parse(String),
    #[error("unsupported OpenAPI version {0}; expected 3.1.x")]
    UnsupportedVersion(String),
    #[error("path {path} has no operation")]
    EmptyPath { path: String },
    #[error("operation at {method} {path} has no operationId")]
    MissingOperationId { method: String, path: String },
    #[error("duplicate operationId {operation_id}")]
    DuplicateOperationId { operation_id: String },
    #[error("path parameter {parameter} in {path} must be declared as a required path parameter")]
    InvalidPathParameter { parameter: String, path: String },
    #[error("unsupported HTTP method {method} at {path}")]
    UnsupportedMethod { method: String, path: String },
}

#[derive(Debug, Deserialize)]
struct RawDocument {
    openapi: String,
    info: RawInfo,
    paths: BTreeMap<String, RawPathItem>,
}

#[derive(Debug, Deserialize)]
struct RawInfo {
    title: String,
    version: String,
}

#[derive(Debug, Default, Deserialize)]
struct RawPathItem {
    #[serde(default)]
    parameters: Vec<RawParameter>,
    delete: Option<RawOperation>,
    get: Option<RawOperation>,
    head: Option<RawOperation>,
    options: Option<RawOperation>,
    patch: Option<RawOperation>,
    post: Option<RawOperation>,
    put: Option<RawOperation>,
    trace: Option<RawOperation>,
}

#[derive(Debug, Deserialize)]
struct RawOperation {
    #[serde(rename = "operationId")]
    operation_id: Option<String>,
    #[serde(default)]
    parameters: Vec<RawParameter>,
    #[serde(rename = "requestBody")]
    request_body: Option<serde_json::Value>,
    #[serde(default)]
    responses: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum RawParameter {
    Inline {
        name: String,
        #[serde(rename = "in")]
        location: String,
        #[serde(default)]
        required: bool,
    },
    Reference {
        #[serde(rename = "$ref")]
        reference: String,
    },
}

impl ApiSpec {
    pub fn from_path(path: impl AsRef<Path>) -> Result<Self, IngestionError> {
        let path = path.as_ref();
        let source = fs::read_to_string(path).map_err(|error| IngestionError::Read {
            path: path.to_path_buf(),
            message: error.to_string(),
        })?;
        Self::parse(&source)
    }

    pub fn parse(source: &str) -> Result<Self, IngestionError> {
        let raw_value: serde_json::Value = yaml_serde::from_str(source)
            .map_err(|error| IngestionError::Parse(error.to_string()))?;
        let raw: RawDocument = serde_json::from_value(raw_value.clone())
            .map_err(|error| IngestionError::Parse(error.to_string()))?;

        if !raw.openapi.starts_with("3.1.") {
            return Err(IngestionError::UnsupportedVersion(raw.openapi));
        }

        normalize_document(raw)
    }
}

fn normalize_document(raw: RawDocument) -> Result<ApiSpec, IngestionError> {
    let mut operations = Vec::new();
    let mut operation_ids = BTreeSet::new();
    let mut references = BTreeSet::new();

    for (path, item) in raw.paths {
        operations.extend(normalize_path(
            &path,
            item,
            &mut operation_ids,
            &mut references,
        )?);
    }
    operations.sort_by(|left, right| {
        left.path
            .cmp(&right.path)
            .then(left.method.cmp(&right.method))
    });

    Ok(ApiSpec {
        openapi_version: raw.openapi,
        title: raw.info.title,
        version: raw.info.version,
        operations,
        references: references.into_iter().collect(),
    })
}

fn normalize_path(
    path: &str,
    item: RawPathItem,
    operation_ids: &mut BTreeSet<String>,
    references: &mut BTreeSet<String>,
) -> Result<Vec<Operation>, IngestionError> {
    let methods = [
        ("delete", HttpMethod::Delete, item.delete),
        ("get", HttpMethod::Get, item.get),
        ("head", HttpMethod::Head, item.head),
        ("options", HttpMethod::Options, item.options),
        ("patch", HttpMethod::Patch, item.patch),
        ("post", HttpMethod::Post, item.post),
        ("put", HttpMethod::Put, item.put),
        ("trace", HttpMethod::Trace, item.trace),
    ];
    let mut operations = Vec::new();
    for (method_name, method, operation) in methods {
        let Some(operation) = operation else {
            continue;
        };
        let context = NormalizationContext {
            path,
            method_name,
            path_parameters: &item.parameters,
            operation_ids,
            references,
        };
        operations.push(normalize_operation(operation, method, context)?);
    }
    if operations.is_empty() {
        return Err(IngestionError::EmptyPath {
            path: path.to_string(),
        });
    }
    Ok(operations)
}

struct NormalizationContext<'a> {
    path: &'a str,
    method_name: &'a str,
    path_parameters: &'a [RawParameter],
    operation_ids: &'a mut BTreeSet<String>,
    references: &'a mut BTreeSet<String>,
}

fn normalize_operation(
    operation: RawOperation,
    method: HttpMethod,
    context: NormalizationContext<'_>,
) -> Result<Operation, IngestionError> {
    let operation_id =
        operation
            .operation_id
            .ok_or_else(|| IngestionError::MissingOperationId {
                method: context.method_name.to_string(),
                path: context.path.to_string(),
            })?;
    if !context.operation_ids.insert(operation_id.clone()) {
        return Err(IngestionError::DuplicateOperationId { operation_id });
    }
    let parameters = normalize_parameters(
        context.path,
        context.path_parameters,
        &operation.parameters,
        context.references,
    )?;
    validate_path_parameters(context.path, &parameters, context.references)?;
    Ok(Operation {
        operation_id,
        method,
        path: context.path.to_string(),
        parameters,
        request_body: operation.request_body.is_some(),
        response_statuses: operation.responses.into_keys().collect(),
    })
}

fn normalize_parameters(
    path: &str,
    path_parameters: &[RawParameter],
    operation_parameters: &[RawParameter],
    references: &mut BTreeSet<String>,
) -> Result<Vec<Parameter>, IngestionError> {
    let mut parameters = Vec::new();
    for parameter in path_parameters.iter().chain(operation_parameters) {
        match parameter {
            RawParameter::Inline {
                name,
                location,
                required,
            } => parameters.push(Parameter {
                name: name.clone(),
                location: parse_parameter_location(location, path)?,
                required: *required,
            }),
            RawParameter::Reference { reference } => {
                references.insert(reference.clone());
            }
        }
    }
    Ok(parameters)
}

fn validate_path_parameters(
    path: &str,
    parameters: &[Parameter],
    references: &BTreeSet<String>,
) -> Result<(), IngestionError> {
    for parameter_name in path_parameters(path) {
        let declared = parameters.iter().any(|parameter| {
            parameter.name == parameter_name
                && parameter.location == ParameterLocation::Path
                && parameter.required
        });
        let referenced = references
            .iter()
            .any(|reference| reference.contains("parameters"));
        if !declared && !referenced {
            return Err(IngestionError::InvalidPathParameter {
                parameter: parameter_name,
                path: path.to_string(),
            });
        }
    }
    Ok(())
}

fn parse_parameter_location(
    location: &str,
    path: &str,
) -> Result<ParameterLocation, IngestionError> {
    match location {
        "query" => Ok(ParameterLocation::Query),
        "header" => Ok(ParameterLocation::Header),
        "path" => Ok(ParameterLocation::Path),
        "cookie" => Ok(ParameterLocation::Cookie),
        _ => Err(IngestionError::Parse(format!(
            "unsupported parameter location {location} at {path}"
        ))),
    }
}

fn path_parameters(path: &str) -> Vec<String> {
    path.split('{')
        .skip(1)
        .filter_map(|segment| segment.split('}').next())
        .map(ToOwned::to_owned)
        .collect()
}
