name: Godlint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  godlint:
    name: Check repository with Godlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Godlint
        uses: tomerwave/godlint@c8b7fbf11b0bf26dd4e23db30ec54f708f7391fe # v1
        with:
          version: 0.7.0
          summary: true
